[package]
name = "notice-ai"
version.workspace = true
edition.workspace = true

[dependencies]
notice-core = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
