[package]
name = "notice-crawler"
version.workspace = true
edition.workspace = true

[dependencies]
notice-core = { workspace = true }
reqwest = { workspace = true }
scraper = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
