[package]
name = "notice-auth"
version.workspace = true
edition.workspace = true

[dependencies]
notice-core = { workspace = true }
argon2 = "0.5"
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
